[[sect_introduction]]

== Introduction

This software package contains components for text mining in scientific publicatons.
Current package contains the following components:

- PDF-to-XMI converter: for transforming PDF documents (publication full-texts) to XMI format.
- Named entity recognizer: for identifying named entities in XMI document (supports English and German)

To learn more about each component you can refer to its corresponding section in this manual, and to find example code
 you can refer to the corresponding test classes for each component.

=== Useful links
Get sources from GitHub:

https://github.com/openminted/uc-tdm-socialsciences

To use the latest snapshot, please add the following piece to your pom file:

--------------------------------------
<repository>
    <id>openminted.snapshots</id>
    <name>OpenMinTeD Project Snapshot Repository</name>
    <url>https://repo.openminted.eu/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

<dependencies>
    <dependency>
        <groupId>eu.openminted.uc-tdm-socialsciences</groupId>
        <artifactId>eu.openminted.uc-tdm-socialsciences</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <type>pom</type>
    </dependency>
</dependencies>
--------------------------------------

Developers mailing list (request to join):

https://groups.google.com/forum/#!forum/uc-tdm-socialsciences-developers

//add [about us] page like https://dkpro.github.io/dkpro-core/info/
//It would be helpful if answers for the following questions are provided:
//- What can I do with this project?
//- Where can I find examples for using these components?
