[[sect_introduction]]

== Introduction

This software package contains components for text mining in scientific publicatons.
Current package contains the following components:

- PDF-to-XMI converter: for transforming PDF documents (publication full-texts) to XMI format.
- Named entity recognizer: for identifying named entities in XMI document (supports English and German)

To learn more about each component you can refer to its corresponding section in this manual, and to find example code
 you can refer to the corresponding test classes for each component.

=== Useful links
Get sources from GitHub:

https://github.com/openminted/uc-tdm-socialsciences

To use the latest release, please add the following piece to your pom file:

--------------------------------------
<repository>
    <id>openminted.releases</id>
    <name>OpenMinTeD Project Release Repository</name>
    <url>https://repo.openminted.eu/content/repositories/releases</url>
</repository>

<dependencies>
    <dependency>
        <groupId>eu.openminted.uc.socialsciences</groupId>
        <artifactId>eu.openminted.uc.socialsciences</artifactId>
        <version>1.0.0</version>
        <type>pom</type>
    </dependency>
</dependencies>
--------------------------------------

To use the latest snapshot, please add the following piece to your pom file:

--------------------------------------
<repository>
    <id>openminted.snapshots</id>
    <name>OpenMinTeD Project Snapshot Repository</name>
    <url>https://repo.openminted.eu/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

<dependencies>
    <dependency>
        <groupId>eu.openminted.uc.socialsciences</groupId>
        <artifactId>eu.openminted.uc.socialsciences</artifactId>
        <version>1.0.1-SNAPSHOT</version>
        <type>pom</type>
    </dependency>
</dependencies>
--------------------------------------

Developers mailing list (request to join):

https://groups.google.com/forum/#!forum/uc-tdm-socialsciences-developers

//add [about us] page like https://dkpro.github.io/dkpro-core/info/
//It would be helpful if answers for the following questions are provided:
//- What can I do with this project?
//- Where can I find examples for using these components?

=== Acknowledgment
This work has received funding from the European Union's Horizon 2020 research and innovation program
(H2020-EINFRA-2014-2) under grant agreement № 654021. This work has been produced as part of the 
OpenMinTeD (http://openminted.eu/) project. It reflects only the authors’ work in the context of 
the project and the Union is not liable for any use that may be made of the software and information
 contained therein.